


console.log(10 == 10)
console.log(10 != 10)
console.log(12 == 'Привет')
console.log(10 < 11)
console.log(12 > 20)
console.log(true && true)
console.log(true && false)
console.log(false && true)
console.log(false || true)
console.log(true || false)
console.log(true || true)
console.log(10 <= 10)
console.log(18 <= 20)
console.log(50 >= 50)
console.log(51 >= 50)
console.log({} === {})
console.log({} == {})